// Code generated by ent, DO NOT EDIT.

package pahead

import (
	"purchase/infra/persistence/dal/db/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PAHead {
	return predicate.PAHead(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldCode, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldState, v))
}

// PayAmount applies equality check predicate on the "pay_amount" field. It's identical to PayAmountEQ.
func PayAmount(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldPayAmount, v))
}

// Applicant applies equality check predicate on the "applicant" field. It's identical to ApplicantEQ.
func Applicant(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldApplicant, v))
}

// Department applies equality check predicate on the "department" field. It's identical to DepartmentEQ.
func Department(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldDepartment, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContainsFold(FieldCode, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContainsFold(FieldState, v))
}

// PayAmountEQ applies the EQ predicate on the "pay_amount" field.
func PayAmountEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldPayAmount, v))
}

// PayAmountNEQ applies the NEQ predicate on the "pay_amount" field.
func PayAmountNEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNEQ(FieldPayAmount, v))
}

// PayAmountIn applies the In predicate on the "pay_amount" field.
func PayAmountIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldIn(FieldPayAmount, vs...))
}

// PayAmountNotIn applies the NotIn predicate on the "pay_amount" field.
func PayAmountNotIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNotIn(FieldPayAmount, vs...))
}

// PayAmountGT applies the GT predicate on the "pay_amount" field.
func PayAmountGT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGT(FieldPayAmount, v))
}

// PayAmountGTE applies the GTE predicate on the "pay_amount" field.
func PayAmountGTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGTE(FieldPayAmount, v))
}

// PayAmountLT applies the LT predicate on the "pay_amount" field.
func PayAmountLT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLT(FieldPayAmount, v))
}

// PayAmountLTE applies the LTE predicate on the "pay_amount" field.
func PayAmountLTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLTE(FieldPayAmount, v))
}

// PayAmountContains applies the Contains predicate on the "pay_amount" field.
func PayAmountContains(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContains(FieldPayAmount, v))
}

// PayAmountHasPrefix applies the HasPrefix predicate on the "pay_amount" field.
func PayAmountHasPrefix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasPrefix(FieldPayAmount, v))
}

// PayAmountHasSuffix applies the HasSuffix predicate on the "pay_amount" field.
func PayAmountHasSuffix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasSuffix(FieldPayAmount, v))
}

// PayAmountEqualFold applies the EqualFold predicate on the "pay_amount" field.
func PayAmountEqualFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEqualFold(FieldPayAmount, v))
}

// PayAmountContainsFold applies the ContainsFold predicate on the "pay_amount" field.
func PayAmountContainsFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContainsFold(FieldPayAmount, v))
}

// ApplicantEQ applies the EQ predicate on the "applicant" field.
func ApplicantEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldApplicant, v))
}

// ApplicantNEQ applies the NEQ predicate on the "applicant" field.
func ApplicantNEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNEQ(FieldApplicant, v))
}

// ApplicantIn applies the In predicate on the "applicant" field.
func ApplicantIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldIn(FieldApplicant, vs...))
}

// ApplicantNotIn applies the NotIn predicate on the "applicant" field.
func ApplicantNotIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNotIn(FieldApplicant, vs...))
}

// ApplicantGT applies the GT predicate on the "applicant" field.
func ApplicantGT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGT(FieldApplicant, v))
}

// ApplicantGTE applies the GTE predicate on the "applicant" field.
func ApplicantGTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGTE(FieldApplicant, v))
}

// ApplicantLT applies the LT predicate on the "applicant" field.
func ApplicantLT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLT(FieldApplicant, v))
}

// ApplicantLTE applies the LTE predicate on the "applicant" field.
func ApplicantLTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLTE(FieldApplicant, v))
}

// ApplicantContains applies the Contains predicate on the "applicant" field.
func ApplicantContains(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContains(FieldApplicant, v))
}

// ApplicantHasPrefix applies the HasPrefix predicate on the "applicant" field.
func ApplicantHasPrefix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasPrefix(FieldApplicant, v))
}

// ApplicantHasSuffix applies the HasSuffix predicate on the "applicant" field.
func ApplicantHasSuffix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasSuffix(FieldApplicant, v))
}

// ApplicantEqualFold applies the EqualFold predicate on the "applicant" field.
func ApplicantEqualFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEqualFold(FieldApplicant, v))
}

// ApplicantContainsFold applies the ContainsFold predicate on the "applicant" field.
func ApplicantContainsFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContainsFold(FieldApplicant, v))
}

// DepartmentEQ applies the EQ predicate on the "department" field.
func DepartmentEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldDepartment, v))
}

// DepartmentNEQ applies the NEQ predicate on the "department" field.
func DepartmentNEQ(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNEQ(FieldDepartment, v))
}

// DepartmentIn applies the In predicate on the "department" field.
func DepartmentIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldIn(FieldDepartment, vs...))
}

// DepartmentNotIn applies the NotIn predicate on the "department" field.
func DepartmentNotIn(vs ...string) predicate.PAHead {
	return predicate.PAHead(sql.FieldNotIn(FieldDepartment, vs...))
}

// DepartmentGT applies the GT predicate on the "department" field.
func DepartmentGT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGT(FieldDepartment, v))
}

// DepartmentGTE applies the GTE predicate on the "department" field.
func DepartmentGTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldGTE(FieldDepartment, v))
}

// DepartmentLT applies the LT predicate on the "department" field.
func DepartmentLT(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLT(FieldDepartment, v))
}

// DepartmentLTE applies the LTE predicate on the "department" field.
func DepartmentLTE(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldLTE(FieldDepartment, v))
}

// DepartmentContains applies the Contains predicate on the "department" field.
func DepartmentContains(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContains(FieldDepartment, v))
}

// DepartmentHasPrefix applies the HasPrefix predicate on the "department" field.
func DepartmentHasPrefix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasPrefix(FieldDepartment, v))
}

// DepartmentHasSuffix applies the HasSuffix predicate on the "department" field.
func DepartmentHasSuffix(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldHasSuffix(FieldDepartment, v))
}

// DepartmentIsNil applies the IsNil predicate on the "department" field.
func DepartmentIsNil() predicate.PAHead {
	return predicate.PAHead(sql.FieldIsNull(FieldDepartment))
}

// DepartmentNotNil applies the NotNil predicate on the "department" field.
func DepartmentNotNil() predicate.PAHead {
	return predicate.PAHead(sql.FieldNotNull(FieldDepartment))
}

// DepartmentEqualFold applies the EqualFold predicate on the "department" field.
func DepartmentEqualFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldEqualFold(FieldDepartment, v))
}

// DepartmentContainsFold applies the ContainsFold predicate on the "department" field.
func DepartmentContainsFold(v string) predicate.PAHead {
	return predicate.PAHead(sql.FieldContainsFold(FieldDepartment, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PAHead {
	return predicate.PAHead(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PAHead) predicate.PAHead {
	return predicate.PAHead(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PAHead) predicate.PAHead {
	return predicate.PAHead(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PAHead) predicate.PAHead {
	return predicate.PAHead(sql.NotPredicates(p))
}
