// Code generated by ent, DO NOT EDIT.

package failedmessage

import (
	"purchase/infra/persistence/dal/db/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldID, id))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldMessageID, v))
}

// Topic applies equality check predicate on the "topic" field. It's identical to TopicEQ.
func Topic(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldTopic, v))
}

// BizCode applies equality check predicate on the "biz_code" field. It's identical to BizCodeEQ.
func BizCode(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldBizCode, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldBody, v))
}

// Header applies equality check predicate on the "header" field. It's identical to HeaderEQ.
func Header(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldHeader, v))
}

// ErrorMsg applies equality check predicate on the "error_msg" field. It's identical to ErrorMsgEQ.
func ErrorMsg(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldErrorMsg, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldState, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldRetryCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContainsFold(FieldMessageID, v))
}

// TopicEQ applies the EQ predicate on the "topic" field.
func TopicEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldTopic, v))
}

// TopicNEQ applies the NEQ predicate on the "topic" field.
func TopicNEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldTopic, v))
}

// TopicIn applies the In predicate on the "topic" field.
func TopicIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldTopic, vs...))
}

// TopicNotIn applies the NotIn predicate on the "topic" field.
func TopicNotIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldTopic, vs...))
}

// TopicGT applies the GT predicate on the "topic" field.
func TopicGT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldTopic, v))
}

// TopicGTE applies the GTE predicate on the "topic" field.
func TopicGTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldTopic, v))
}

// TopicLT applies the LT predicate on the "topic" field.
func TopicLT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldTopic, v))
}

// TopicLTE applies the LTE predicate on the "topic" field.
func TopicLTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldTopic, v))
}

// TopicContains applies the Contains predicate on the "topic" field.
func TopicContains(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContains(FieldTopic, v))
}

// TopicHasPrefix applies the HasPrefix predicate on the "topic" field.
func TopicHasPrefix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasPrefix(FieldTopic, v))
}

// TopicHasSuffix applies the HasSuffix predicate on the "topic" field.
func TopicHasSuffix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasSuffix(FieldTopic, v))
}

// TopicEqualFold applies the EqualFold predicate on the "topic" field.
func TopicEqualFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEqualFold(FieldTopic, v))
}

// TopicContainsFold applies the ContainsFold predicate on the "topic" field.
func TopicContainsFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContainsFold(FieldTopic, v))
}

// BizCodeEQ applies the EQ predicate on the "biz_code" field.
func BizCodeEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldBizCode, v))
}

// BizCodeNEQ applies the NEQ predicate on the "biz_code" field.
func BizCodeNEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldBizCode, v))
}

// BizCodeIn applies the In predicate on the "biz_code" field.
func BizCodeIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldBizCode, vs...))
}

// BizCodeNotIn applies the NotIn predicate on the "biz_code" field.
func BizCodeNotIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldBizCode, vs...))
}

// BizCodeGT applies the GT predicate on the "biz_code" field.
func BizCodeGT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldBizCode, v))
}

// BizCodeGTE applies the GTE predicate on the "biz_code" field.
func BizCodeGTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldBizCode, v))
}

// BizCodeLT applies the LT predicate on the "biz_code" field.
func BizCodeLT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldBizCode, v))
}

// BizCodeLTE applies the LTE predicate on the "biz_code" field.
func BizCodeLTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldBizCode, v))
}

// BizCodeContains applies the Contains predicate on the "biz_code" field.
func BizCodeContains(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContains(FieldBizCode, v))
}

// BizCodeHasPrefix applies the HasPrefix predicate on the "biz_code" field.
func BizCodeHasPrefix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasPrefix(FieldBizCode, v))
}

// BizCodeHasSuffix applies the HasSuffix predicate on the "biz_code" field.
func BizCodeHasSuffix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasSuffix(FieldBizCode, v))
}

// BizCodeEqualFold applies the EqualFold predicate on the "biz_code" field.
func BizCodeEqualFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEqualFold(FieldBizCode, v))
}

// BizCodeContainsFold applies the ContainsFold predicate on the "biz_code" field.
func BizCodeContainsFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContainsFold(FieldBizCode, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContainsFold(FieldBody, v))
}

// HeaderEQ applies the EQ predicate on the "header" field.
func HeaderEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldHeader, v))
}

// HeaderNEQ applies the NEQ predicate on the "header" field.
func HeaderNEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldHeader, v))
}

// HeaderIn applies the In predicate on the "header" field.
func HeaderIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldHeader, vs...))
}

// HeaderNotIn applies the NotIn predicate on the "header" field.
func HeaderNotIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldHeader, vs...))
}

// HeaderGT applies the GT predicate on the "header" field.
func HeaderGT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldHeader, v))
}

// HeaderGTE applies the GTE predicate on the "header" field.
func HeaderGTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldHeader, v))
}

// HeaderLT applies the LT predicate on the "header" field.
func HeaderLT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldHeader, v))
}

// HeaderLTE applies the LTE predicate on the "header" field.
func HeaderLTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldHeader, v))
}

// HeaderContains applies the Contains predicate on the "header" field.
func HeaderContains(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContains(FieldHeader, v))
}

// HeaderHasPrefix applies the HasPrefix predicate on the "header" field.
func HeaderHasPrefix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasPrefix(FieldHeader, v))
}

// HeaderHasSuffix applies the HasSuffix predicate on the "header" field.
func HeaderHasSuffix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasSuffix(FieldHeader, v))
}

// HeaderEqualFold applies the EqualFold predicate on the "header" field.
func HeaderEqualFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEqualFold(FieldHeader, v))
}

// HeaderContainsFold applies the ContainsFold predicate on the "header" field.
func HeaderContainsFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContainsFold(FieldHeader, v))
}

// ErrorMsgEQ applies the EQ predicate on the "error_msg" field.
func ErrorMsgEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldErrorMsg, v))
}

// ErrorMsgNEQ applies the NEQ predicate on the "error_msg" field.
func ErrorMsgNEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldErrorMsg, v))
}

// ErrorMsgIn applies the In predicate on the "error_msg" field.
func ErrorMsgIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldErrorMsg, vs...))
}

// ErrorMsgNotIn applies the NotIn predicate on the "error_msg" field.
func ErrorMsgNotIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldErrorMsg, vs...))
}

// ErrorMsgGT applies the GT predicate on the "error_msg" field.
func ErrorMsgGT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldErrorMsg, v))
}

// ErrorMsgGTE applies the GTE predicate on the "error_msg" field.
func ErrorMsgGTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldErrorMsg, v))
}

// ErrorMsgLT applies the LT predicate on the "error_msg" field.
func ErrorMsgLT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldErrorMsg, v))
}

// ErrorMsgLTE applies the LTE predicate on the "error_msg" field.
func ErrorMsgLTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldErrorMsg, v))
}

// ErrorMsgContains applies the Contains predicate on the "error_msg" field.
func ErrorMsgContains(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContains(FieldErrorMsg, v))
}

// ErrorMsgHasPrefix applies the HasPrefix predicate on the "error_msg" field.
func ErrorMsgHasPrefix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasPrefix(FieldErrorMsg, v))
}

// ErrorMsgHasSuffix applies the HasSuffix predicate on the "error_msg" field.
func ErrorMsgHasSuffix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasSuffix(FieldErrorMsg, v))
}

// ErrorMsgEqualFold applies the EqualFold predicate on the "error_msg" field.
func ErrorMsgEqualFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEqualFold(FieldErrorMsg, v))
}

// ErrorMsgContainsFold applies the ContainsFold predicate on the "error_msg" field.
func ErrorMsgContainsFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContainsFold(FieldErrorMsg, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldContainsFold(FieldState, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldRetryCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FailedMessage {
	return predicate.FailedMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FailedMessage) predicate.FailedMessage {
	return predicate.FailedMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FailedMessage) predicate.FailedMessage {
	return predicate.FailedMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FailedMessage) predicate.FailedMessage {
	return predicate.FailedMessage(sql.NotPredicates(p))
}
