// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TAsyncTaskColumns holds the columns for the "t_async_task" table.
	TAsyncTaskColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "task_id", Type: field.TypeString},
		{Name: "task_type", Type: field.TypeString},
		{Name: "task_name", Type: field.TypeString},
		{Name: "task_data", Type: field.TypeString},
		{Name: "task_state", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// TAsyncTaskTable holds the schema information for the "t_async_task" table.
	TAsyncTaskTable = &schema.Table{
		Name:       "t_async_task",
		Columns:    TAsyncTaskColumns,
		PrimaryKey: []*schema.Column{TAsyncTaskColumns[0]},
	}
	// PaHeadsColumns holds the columns for the "pa_heads" table.
	PaHeadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString},
		{Name: "state", Type: field.TypeString},
		{Name: "pay_amount", Type: field.TypeString},
		{Name: "applicant", Type: field.TypeString},
		{Name: "department", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// PaHeadsTable holds the schema information for the "pa_heads" table.
	PaHeadsTable = &schema.Table{
		Name:       "pa_heads",
		Columns:    PaHeadsColumns,
		PrimaryKey: []*schema.Column{PaHeadsColumns[0]},
	}
	// PaRowsColumns holds the columns for the "pa_rows" table.
	PaRowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "doc_code", Type: field.TypeString},
		{Name: "order_code", Type: field.TypeString},
		{Name: "row_currency", Type: field.TypeString},
		{Name: "tax_ratio", Type: field.TypeString},
		{Name: "initial_amount", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// PaRowsTable holds the schema information for the "pa_rows" table.
	PaRowsTable = &schema.Table{
		Name:       "pa_rows",
		Columns:    PaRowsColumns,
		PrimaryKey: []*schema.Column{PaRowsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TAsyncTaskTable,
		PaHeadsTable,
		PaRowsTable,
	}
)

func init() {
	TAsyncTaskTable.Annotation = &entsql.Annotation{
		Table: "t_async_task",
	}
}
