// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"purchase/infra/persistence/dal/db/ent/asynctask"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AsyncTaskCreate is the builder for creating a AsyncTask entity.
type AsyncTaskCreate struct {
	config
	mutation *AsyncTaskMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (atc *AsyncTaskCreate) SetTaskID(s string) *AsyncTaskCreate {
	atc.mutation.SetTaskID(s)
	return atc
}

// SetTaskType sets the "task_type" field.
func (atc *AsyncTaskCreate) SetTaskType(s string) *AsyncTaskCreate {
	atc.mutation.SetTaskType(s)
	return atc
}

// SetTaskName sets the "task_name" field.
func (atc *AsyncTaskCreate) SetTaskName(s string) *AsyncTaskCreate {
	atc.mutation.SetTaskName(s)
	return atc
}

// SetTaskData sets the "task_data" field.
func (atc *AsyncTaskCreate) SetTaskData(s string) *AsyncTaskCreate {
	atc.mutation.SetTaskData(s)
	return atc
}

// SetState sets the "state" field.
func (atc *AsyncTaskCreate) SetState(s string) *AsyncTaskCreate {
	atc.mutation.SetState(s)
	return atc
}

// SetCreatedAt sets the "created_at" field.
func (atc *AsyncTaskCreate) SetCreatedAt(t time.Time) *AsyncTaskCreate {
	atc.mutation.SetCreatedAt(t)
	return atc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (atc *AsyncTaskCreate) SetNillableCreatedAt(t *time.Time) *AsyncTaskCreate {
	if t != nil {
		atc.SetCreatedAt(*t)
	}
	return atc
}

// SetUpdatedAt sets the "updated_at" field.
func (atc *AsyncTaskCreate) SetUpdatedAt(t time.Time) *AsyncTaskCreate {
	atc.mutation.SetUpdatedAt(t)
	return atc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (atc *AsyncTaskCreate) SetNillableUpdatedAt(t *time.Time) *AsyncTaskCreate {
	if t != nil {
		atc.SetUpdatedAt(*t)
	}
	return atc
}

// SetID sets the "id" field.
func (atc *AsyncTaskCreate) SetID(i int64) *AsyncTaskCreate {
	atc.mutation.SetID(i)
	return atc
}

// Mutation returns the AsyncTaskMutation object of the builder.
func (atc *AsyncTaskCreate) Mutation() *AsyncTaskMutation {
	return atc.mutation
}

// Save creates the AsyncTask in the database.
func (atc *AsyncTaskCreate) Save(ctx context.Context) (*AsyncTask, error) {
	atc.defaults()
	return withHooks(ctx, atc.sqlSave, atc.mutation, atc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (atc *AsyncTaskCreate) SaveX(ctx context.Context) *AsyncTask {
	v, err := atc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atc *AsyncTaskCreate) Exec(ctx context.Context) error {
	_, err := atc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atc *AsyncTaskCreate) ExecX(ctx context.Context) {
	if err := atc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (atc *AsyncTaskCreate) defaults() {
	if _, ok := atc.mutation.CreatedAt(); !ok {
		v := asynctask.DefaultCreatedAt()
		atc.mutation.SetCreatedAt(v)
	}
	if _, ok := atc.mutation.UpdatedAt(); !ok {
		v := asynctask.DefaultUpdatedAt()
		atc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atc *AsyncTaskCreate) check() error {
	if _, ok := atc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "AsyncTask.task_id"`)}
	}
	if _, ok := atc.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "AsyncTask.task_type"`)}
	}
	if _, ok := atc.mutation.TaskName(); !ok {
		return &ValidationError{Name: "task_name", err: errors.New(`ent: missing required field "AsyncTask.task_name"`)}
	}
	if _, ok := atc.mutation.TaskData(); !ok {
		return &ValidationError{Name: "task_data", err: errors.New(`ent: missing required field "AsyncTask.task_data"`)}
	}
	if _, ok := atc.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "AsyncTask.state"`)}
	}
	if _, ok := atc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AsyncTask.created_at"`)}
	}
	if _, ok := atc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AsyncTask.updated_at"`)}
	}
	return nil
}

func (atc *AsyncTaskCreate) sqlSave(ctx context.Context) (*AsyncTask, error) {
	if err := atc.check(); err != nil {
		return nil, err
	}
	_node, _spec := atc.createSpec()
	if err := sqlgraph.CreateNode(ctx, atc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	atc.mutation.id = &_node.ID
	atc.mutation.done = true
	return _node, nil
}

func (atc *AsyncTaskCreate) createSpec() (*AsyncTask, *sqlgraph.CreateSpec) {
	var (
		_node = &AsyncTask{config: atc.config}
		_spec = sqlgraph.NewCreateSpec(asynctask.Table, sqlgraph.NewFieldSpec(asynctask.FieldID, field.TypeInt64))
	)
	if id, ok := atc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := atc.mutation.TaskID(); ok {
		_spec.SetField(asynctask.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := atc.mutation.TaskType(); ok {
		_spec.SetField(asynctask.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := atc.mutation.TaskName(); ok {
		_spec.SetField(asynctask.FieldTaskName, field.TypeString, value)
		_node.TaskName = value
	}
	if value, ok := atc.mutation.TaskData(); ok {
		_spec.SetField(asynctask.FieldTaskData, field.TypeString, value)
		_node.TaskData = value
	}
	if value, ok := atc.mutation.State(); ok {
		_spec.SetField(asynctask.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := atc.mutation.CreatedAt(); ok {
		_spec.SetField(asynctask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := atc.mutation.UpdatedAt(); ok {
		_spec.SetField(asynctask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AsyncTaskCreateBulk is the builder for creating many AsyncTask entities in bulk.
type AsyncTaskCreateBulk struct {
	config
	err      error
	builders []*AsyncTaskCreate
}

// Save creates the AsyncTask entities in the database.
func (atcb *AsyncTaskCreateBulk) Save(ctx context.Context) ([]*AsyncTask, error) {
	if atcb.err != nil {
		return nil, atcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(atcb.builders))
	nodes := make([]*AsyncTask, len(atcb.builders))
	mutators := make([]Mutator, len(atcb.builders))
	for i := range atcb.builders {
		func(i int, root context.Context) {
			builder := atcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AsyncTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, atcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, atcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, atcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (atcb *AsyncTaskCreateBulk) SaveX(ctx context.Context) []*AsyncTask {
	v, err := atcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atcb *AsyncTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := atcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atcb *AsyncTaskCreateBulk) ExecX(ctx context.Context) {
	if err := atcb.Exec(ctx); err != nil {
		panic(err)
	}
}
