// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"purchase/infra/persistence/dal/db/ent/asynctask"
	"purchase/infra/persistence/dal/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AsyncTaskQuery is the builder for querying AsyncTask entities.
type AsyncTaskQuery struct {
	config
	ctx        *QueryContext
	order      []asynctask.OrderOption
	inters     []Interceptor
	predicates []predicate.AsyncTask
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AsyncTaskQuery builder.
func (atq *AsyncTaskQuery) Where(ps ...predicate.AsyncTask) *AsyncTaskQuery {
	atq.predicates = append(atq.predicates, ps...)
	return atq
}

// Limit the number of records to be returned by this query.
func (atq *AsyncTaskQuery) Limit(limit int) *AsyncTaskQuery {
	atq.ctx.Limit = &limit
	return atq
}

// Offset to start from.
func (atq *AsyncTaskQuery) Offset(offset int) *AsyncTaskQuery {
	atq.ctx.Offset = &offset
	return atq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (atq *AsyncTaskQuery) Unique(unique bool) *AsyncTaskQuery {
	atq.ctx.Unique = &unique
	return atq
}

// Order specifies how the records should be ordered.
func (atq *AsyncTaskQuery) Order(o ...asynctask.OrderOption) *AsyncTaskQuery {
	atq.order = append(atq.order, o...)
	return atq
}

// First returns the first AsyncTask entity from the query.
// Returns a *NotFoundError when no AsyncTask was found.
func (atq *AsyncTaskQuery) First(ctx context.Context) (*AsyncTask, error) {
	nodes, err := atq.Limit(1).All(setContextOp(ctx, atq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{asynctask.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (atq *AsyncTaskQuery) FirstX(ctx context.Context) *AsyncTask {
	node, err := atq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AsyncTask ID from the query.
// Returns a *NotFoundError when no AsyncTask ID was found.
func (atq *AsyncTaskQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = atq.Limit(1).IDs(setContextOp(ctx, atq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{asynctask.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (atq *AsyncTaskQuery) FirstIDX(ctx context.Context) int64 {
	id, err := atq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AsyncTask entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AsyncTask entity is found.
// Returns a *NotFoundError when no AsyncTask entities are found.
func (atq *AsyncTaskQuery) Only(ctx context.Context) (*AsyncTask, error) {
	nodes, err := atq.Limit(2).All(setContextOp(ctx, atq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{asynctask.Label}
	default:
		return nil, &NotSingularError{asynctask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (atq *AsyncTaskQuery) OnlyX(ctx context.Context) *AsyncTask {
	node, err := atq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AsyncTask ID in the query.
// Returns a *NotSingularError when more than one AsyncTask ID is found.
// Returns a *NotFoundError when no entities are found.
func (atq *AsyncTaskQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = atq.Limit(2).IDs(setContextOp(ctx, atq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{asynctask.Label}
	default:
		err = &NotSingularError{asynctask.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (atq *AsyncTaskQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := atq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AsyncTasks.
func (atq *AsyncTaskQuery) All(ctx context.Context) ([]*AsyncTask, error) {
	ctx = setContextOp(ctx, atq.ctx, "All")
	if err := atq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AsyncTask, *AsyncTaskQuery]()
	return withInterceptors[[]*AsyncTask](ctx, atq, qr, atq.inters)
}

// AllX is like All, but panics if an error occurs.
func (atq *AsyncTaskQuery) AllX(ctx context.Context) []*AsyncTask {
	nodes, err := atq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AsyncTask IDs.
func (atq *AsyncTaskQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if atq.ctx.Unique == nil && atq.path != nil {
		atq.Unique(true)
	}
	ctx = setContextOp(ctx, atq.ctx, "IDs")
	if err = atq.Select(asynctask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (atq *AsyncTaskQuery) IDsX(ctx context.Context) []int64 {
	ids, err := atq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (atq *AsyncTaskQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, atq.ctx, "Count")
	if err := atq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, atq, querierCount[*AsyncTaskQuery](), atq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (atq *AsyncTaskQuery) CountX(ctx context.Context) int {
	count, err := atq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (atq *AsyncTaskQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, atq.ctx, "Exist")
	switch _, err := atq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (atq *AsyncTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := atq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AsyncTaskQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (atq *AsyncTaskQuery) Clone() *AsyncTaskQuery {
	if atq == nil {
		return nil
	}
	return &AsyncTaskQuery{
		config:     atq.config,
		ctx:        atq.ctx.Clone(),
		order:      append([]asynctask.OrderOption{}, atq.order...),
		inters:     append([]Interceptor{}, atq.inters...),
		predicates: append([]predicate.AsyncTask{}, atq.predicates...),
		// clone intermediate query.
		sql:  atq.sql.Clone(),
		path: atq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AsyncTask.Query().
//		GroupBy(asynctask.FieldTaskID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (atq *AsyncTaskQuery) GroupBy(field string, fields ...string) *AsyncTaskGroupBy {
	atq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AsyncTaskGroupBy{build: atq}
	grbuild.flds = &atq.ctx.Fields
	grbuild.label = asynctask.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//	}
//
//	client.AsyncTask.Query().
//		Select(asynctask.FieldTaskID).
//		Scan(ctx, &v)
func (atq *AsyncTaskQuery) Select(fields ...string) *AsyncTaskSelect {
	atq.ctx.Fields = append(atq.ctx.Fields, fields...)
	sbuild := &AsyncTaskSelect{AsyncTaskQuery: atq}
	sbuild.label = asynctask.Label
	sbuild.flds, sbuild.scan = &atq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AsyncTaskSelect configured with the given aggregations.
func (atq *AsyncTaskQuery) Aggregate(fns ...AggregateFunc) *AsyncTaskSelect {
	return atq.Select().Aggregate(fns...)
}

func (atq *AsyncTaskQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range atq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, atq); err != nil {
				return err
			}
		}
	}
	for _, f := range atq.ctx.Fields {
		if !asynctask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if atq.path != nil {
		prev, err := atq.path(ctx)
		if err != nil {
			return err
		}
		atq.sql = prev
	}
	return nil
}

func (atq *AsyncTaskQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AsyncTask, error) {
	var (
		nodes = []*AsyncTask{}
		_spec = atq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AsyncTask).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AsyncTask{config: atq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, atq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (atq *AsyncTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := atq.querySpec()
	_spec.Node.Columns = atq.ctx.Fields
	if len(atq.ctx.Fields) > 0 {
		_spec.Unique = atq.ctx.Unique != nil && *atq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, atq.driver, _spec)
}

func (atq *AsyncTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(asynctask.Table, asynctask.Columns, sqlgraph.NewFieldSpec(asynctask.FieldID, field.TypeInt64))
	_spec.From = atq.sql
	if unique := atq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if atq.path != nil {
		_spec.Unique = true
	}
	if fields := atq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asynctask.FieldID)
		for i := range fields {
			if fields[i] != asynctask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := atq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := atq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := atq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := atq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (atq *AsyncTaskQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(atq.driver.Dialect())
	t1 := builder.Table(asynctask.Table)
	columns := atq.ctx.Fields
	if len(columns) == 0 {
		columns = asynctask.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if atq.sql != nil {
		selector = atq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if atq.ctx.Unique != nil && *atq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range atq.predicates {
		p(selector)
	}
	for _, p := range atq.order {
		p(selector)
	}
	if offset := atq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := atq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AsyncTaskGroupBy is the group-by builder for AsyncTask entities.
type AsyncTaskGroupBy struct {
	selector
	build *AsyncTaskQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (atgb *AsyncTaskGroupBy) Aggregate(fns ...AggregateFunc) *AsyncTaskGroupBy {
	atgb.fns = append(atgb.fns, fns...)
	return atgb
}

// Scan applies the selector query and scans the result into the given value.
func (atgb *AsyncTaskGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, atgb.build.ctx, "GroupBy")
	if err := atgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AsyncTaskQuery, *AsyncTaskGroupBy](ctx, atgb.build, atgb, atgb.build.inters, v)
}

func (atgb *AsyncTaskGroupBy) sqlScan(ctx context.Context, root *AsyncTaskQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(atgb.fns))
	for _, fn := range atgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*atgb.flds)+len(atgb.fns))
		for _, f := range *atgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*atgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := atgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AsyncTaskSelect is the builder for selecting fields of AsyncTask entities.
type AsyncTaskSelect struct {
	*AsyncTaskQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ats *AsyncTaskSelect) Aggregate(fns ...AggregateFunc) *AsyncTaskSelect {
	ats.fns = append(ats.fns, fns...)
	return ats
}

// Scan applies the selector query and scans the result into the given value.
func (ats *AsyncTaskSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ats.ctx, "Select")
	if err := ats.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AsyncTaskQuery, *AsyncTaskSelect](ctx, ats.AsyncTaskQuery, ats, ats.inters, v)
}

func (ats *AsyncTaskSelect) sqlScan(ctx context.Context, root *AsyncTaskQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ats.fns))
	for _, fn := range ats.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ats.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
