// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"purchase/infra/persistence/dal/db/ent/migrate"

	"purchase/infra/persistence/dal/db/ent/asynctask"
	"purchase/infra/persistence/dal/db/ent/pahead"
	"purchase/infra/persistence/dal/db/ent/parow"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AsyncTask is the client for interacting with the AsyncTask builders.
	AsyncTask *AsyncTaskClient
	// PAHead is the client for interacting with the PAHead builders.
	PAHead *PAHeadClient
	// PARow is the client for interacting with the PARow builders.
	PARow *PARowClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AsyncTask = NewAsyncTaskClient(c.config)
	c.PAHead = NewPAHeadClient(c.config)
	c.PARow = NewPARowClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		AsyncTask: NewAsyncTaskClient(cfg),
		PAHead:    NewPAHeadClient(cfg),
		PARow:     NewPARowClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		AsyncTask: NewAsyncTaskClient(cfg),
		PAHead:    NewPAHeadClient(cfg),
		PARow:     NewPARowClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AsyncTask.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AsyncTask.Use(hooks...)
	c.PAHead.Use(hooks...)
	c.PARow.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AsyncTask.Intercept(interceptors...)
	c.PAHead.Intercept(interceptors...)
	c.PARow.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AsyncTaskMutation:
		return c.AsyncTask.mutate(ctx, m)
	case *PAHeadMutation:
		return c.PAHead.mutate(ctx, m)
	case *PARowMutation:
		return c.PARow.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AsyncTaskClient is a client for the AsyncTask schema.
type AsyncTaskClient struct {
	config
}

// NewAsyncTaskClient returns a client for the AsyncTask from the given config.
func NewAsyncTaskClient(c config) *AsyncTaskClient {
	return &AsyncTaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `asynctask.Hooks(f(g(h())))`.
func (c *AsyncTaskClient) Use(hooks ...Hook) {
	c.hooks.AsyncTask = append(c.hooks.AsyncTask, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `asynctask.Intercept(f(g(h())))`.
func (c *AsyncTaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.AsyncTask = append(c.inters.AsyncTask, interceptors...)
}

// Create returns a builder for creating a AsyncTask entity.
func (c *AsyncTaskClient) Create() *AsyncTaskCreate {
	mutation := newAsyncTaskMutation(c.config, OpCreate)
	return &AsyncTaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AsyncTask entities.
func (c *AsyncTaskClient) CreateBulk(builders ...*AsyncTaskCreate) *AsyncTaskCreateBulk {
	return &AsyncTaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AsyncTaskClient) MapCreateBulk(slice any, setFunc func(*AsyncTaskCreate, int)) *AsyncTaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AsyncTaskCreateBulk{err: fmt.Errorf("calling to AsyncTaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AsyncTaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AsyncTaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AsyncTask.
func (c *AsyncTaskClient) Update() *AsyncTaskUpdate {
	mutation := newAsyncTaskMutation(c.config, OpUpdate)
	return &AsyncTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AsyncTaskClient) UpdateOne(at *AsyncTask) *AsyncTaskUpdateOne {
	mutation := newAsyncTaskMutation(c.config, OpUpdateOne, withAsyncTask(at))
	return &AsyncTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AsyncTaskClient) UpdateOneID(id int64) *AsyncTaskUpdateOne {
	mutation := newAsyncTaskMutation(c.config, OpUpdateOne, withAsyncTaskID(id))
	return &AsyncTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AsyncTask.
func (c *AsyncTaskClient) Delete() *AsyncTaskDelete {
	mutation := newAsyncTaskMutation(c.config, OpDelete)
	return &AsyncTaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AsyncTaskClient) DeleteOne(at *AsyncTask) *AsyncTaskDeleteOne {
	return c.DeleteOneID(at.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AsyncTaskClient) DeleteOneID(id int64) *AsyncTaskDeleteOne {
	builder := c.Delete().Where(asynctask.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AsyncTaskDeleteOne{builder}
}

// Query returns a query builder for AsyncTask.
func (c *AsyncTaskClient) Query() *AsyncTaskQuery {
	return &AsyncTaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAsyncTask},
		inters: c.Interceptors(),
	}
}

// Get returns a AsyncTask entity by its id.
func (c *AsyncTaskClient) Get(ctx context.Context, id int64) (*AsyncTask, error) {
	return c.Query().Where(asynctask.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AsyncTaskClient) GetX(ctx context.Context, id int64) *AsyncTask {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AsyncTaskClient) Hooks() []Hook {
	return c.hooks.AsyncTask
}

// Interceptors returns the client interceptors.
func (c *AsyncTaskClient) Interceptors() []Interceptor {
	return c.inters.AsyncTask
}

func (c *AsyncTaskClient) mutate(ctx context.Context, m *AsyncTaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AsyncTaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AsyncTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AsyncTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AsyncTaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AsyncTask mutation op: %q", m.Op())
	}
}

// PAHeadClient is a client for the PAHead schema.
type PAHeadClient struct {
	config
}

// NewPAHeadClient returns a client for the PAHead from the given config.
func NewPAHeadClient(c config) *PAHeadClient {
	return &PAHeadClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pahead.Hooks(f(g(h())))`.
func (c *PAHeadClient) Use(hooks ...Hook) {
	c.hooks.PAHead = append(c.hooks.PAHead, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pahead.Intercept(f(g(h())))`.
func (c *PAHeadClient) Intercept(interceptors ...Interceptor) {
	c.inters.PAHead = append(c.inters.PAHead, interceptors...)
}

// Create returns a builder for creating a PAHead entity.
func (c *PAHeadClient) Create() *PAHeadCreate {
	mutation := newPAHeadMutation(c.config, OpCreate)
	return &PAHeadCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PAHead entities.
func (c *PAHeadClient) CreateBulk(builders ...*PAHeadCreate) *PAHeadCreateBulk {
	return &PAHeadCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PAHeadClient) MapCreateBulk(slice any, setFunc func(*PAHeadCreate, int)) *PAHeadCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PAHeadCreateBulk{err: fmt.Errorf("calling to PAHeadClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PAHeadCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PAHeadCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PAHead.
func (c *PAHeadClient) Update() *PAHeadUpdate {
	mutation := newPAHeadMutation(c.config, OpUpdate)
	return &PAHeadUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PAHeadClient) UpdateOne(ph *PAHead) *PAHeadUpdateOne {
	mutation := newPAHeadMutation(c.config, OpUpdateOne, withPAHead(ph))
	return &PAHeadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PAHeadClient) UpdateOneID(id int64) *PAHeadUpdateOne {
	mutation := newPAHeadMutation(c.config, OpUpdateOne, withPAHeadID(id))
	return &PAHeadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PAHead.
func (c *PAHeadClient) Delete() *PAHeadDelete {
	mutation := newPAHeadMutation(c.config, OpDelete)
	return &PAHeadDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PAHeadClient) DeleteOne(ph *PAHead) *PAHeadDeleteOne {
	return c.DeleteOneID(ph.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PAHeadClient) DeleteOneID(id int64) *PAHeadDeleteOne {
	builder := c.Delete().Where(pahead.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PAHeadDeleteOne{builder}
}

// Query returns a query builder for PAHead.
func (c *PAHeadClient) Query() *PAHeadQuery {
	return &PAHeadQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePAHead},
		inters: c.Interceptors(),
	}
}

// Get returns a PAHead entity by its id.
func (c *PAHeadClient) Get(ctx context.Context, id int64) (*PAHead, error) {
	return c.Query().Where(pahead.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PAHeadClient) GetX(ctx context.Context, id int64) *PAHead {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PAHeadClient) Hooks() []Hook {
	return c.hooks.PAHead
}

// Interceptors returns the client interceptors.
func (c *PAHeadClient) Interceptors() []Interceptor {
	return c.inters.PAHead
}

func (c *PAHeadClient) mutate(ctx context.Context, m *PAHeadMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PAHeadCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PAHeadUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PAHeadUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PAHeadDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PAHead mutation op: %q", m.Op())
	}
}

// PARowClient is a client for the PARow schema.
type PARowClient struct {
	config
}

// NewPARowClient returns a client for the PARow from the given config.
func NewPARowClient(c config) *PARowClient {
	return &PARowClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `parow.Hooks(f(g(h())))`.
func (c *PARowClient) Use(hooks ...Hook) {
	c.hooks.PARow = append(c.hooks.PARow, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `parow.Intercept(f(g(h())))`.
func (c *PARowClient) Intercept(interceptors ...Interceptor) {
	c.inters.PARow = append(c.inters.PARow, interceptors...)
}

// Create returns a builder for creating a PARow entity.
func (c *PARowClient) Create() *PARowCreate {
	mutation := newPARowMutation(c.config, OpCreate)
	return &PARowCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PARow entities.
func (c *PARowClient) CreateBulk(builders ...*PARowCreate) *PARowCreateBulk {
	return &PARowCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PARowClient) MapCreateBulk(slice any, setFunc func(*PARowCreate, int)) *PARowCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PARowCreateBulk{err: fmt.Errorf("calling to PARowClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PARowCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PARowCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PARow.
func (c *PARowClient) Update() *PARowUpdate {
	mutation := newPARowMutation(c.config, OpUpdate)
	return &PARowUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PARowClient) UpdateOne(pr *PARow) *PARowUpdateOne {
	mutation := newPARowMutation(c.config, OpUpdateOne, withPARow(pr))
	return &PARowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PARowClient) UpdateOneID(id int64) *PARowUpdateOne {
	mutation := newPARowMutation(c.config, OpUpdateOne, withPARowID(id))
	return &PARowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PARow.
func (c *PARowClient) Delete() *PARowDelete {
	mutation := newPARowMutation(c.config, OpDelete)
	return &PARowDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PARowClient) DeleteOne(pr *PARow) *PARowDeleteOne {
	return c.DeleteOneID(pr.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PARowClient) DeleteOneID(id int64) *PARowDeleteOne {
	builder := c.Delete().Where(parow.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PARowDeleteOne{builder}
}

// Query returns a query builder for PARow.
func (c *PARowClient) Query() *PARowQuery {
	return &PARowQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePARow},
		inters: c.Interceptors(),
	}
}

// Get returns a PARow entity by its id.
func (c *PARowClient) Get(ctx context.Context, id int64) (*PARow, error) {
	return c.Query().Where(parow.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PARowClient) GetX(ctx context.Context, id int64) *PARow {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PARowClient) Hooks() []Hook {
	return c.hooks.PARow
}

// Interceptors returns the client interceptors.
func (c *PARowClient) Interceptors() []Interceptor {
	return c.inters.PARow
}

func (c *PARowClient) mutate(ctx context.Context, m *PARowMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PARowCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PARowUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PARowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PARowDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PARow mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AsyncTask, PAHead, PARow []ent.Hook
	}
	inters struct {
		AsyncTask, PAHead, PARow []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
