// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"purchase/infra/persistence/dal/db/ent/failedmessage"
	"purchase/infra/persistence/dal/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FailedMessageDelete is the builder for deleting a FailedMessage entity.
type FailedMessageDelete struct {
	config
	hooks    []Hook
	mutation *FailedMessageMutation
}

// Where appends a list predicates to the FailedMessageDelete builder.
func (fmd *FailedMessageDelete) Where(ps ...predicate.FailedMessage) *FailedMessageDelete {
	fmd.mutation.Where(ps...)
	return fmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fmd *FailedMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fmd.sqlExec, fmd.mutation, fmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fmd *FailedMessageDelete) ExecX(ctx context.Context) int {
	n, err := fmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fmd *FailedMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(failedmessage.Table, sqlgraph.NewFieldSpec(failedmessage.FieldID, field.TypeInt64))
	if ps := fmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fmd.mutation.done = true
	return affected, err
}

// FailedMessageDeleteOne is the builder for deleting a single FailedMessage entity.
type FailedMessageDeleteOne struct {
	fmd *FailedMessageDelete
}

// Where appends a list predicates to the FailedMessageDelete builder.
func (fmdo *FailedMessageDeleteOne) Where(ps ...predicate.FailedMessage) *FailedMessageDeleteOne {
	fmdo.fmd.mutation.Where(ps...)
	return fmdo
}

// Exec executes the deletion query.
func (fmdo *FailedMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := fmdo.fmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{failedmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fmdo *FailedMessageDeleteOne) ExecX(ctx context.Context) {
	if err := fmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
