// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"purchase/infra/persistence/dal/db/ent/asynctask"
	"purchase/infra/persistence/dal/db/ent/pahead"
	"purchase/infra/persistence/dal/db/ent/parow"
	"purchase/infra/persistence/dal/db/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAsyncTask = "AsyncTask"
	TypePAHead    = "PAHead"
	TypePARow     = "PARow"
)

// AsyncTaskMutation represents an operation that mutates the AsyncTask nodes in the graph.
type AsyncTaskMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	task_id       *string
	task_type     *string
	task_name     *string
	task_data     *string
	state         *string
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*AsyncTask, error)
	predicates    []predicate.AsyncTask
}

var _ ent.Mutation = (*AsyncTaskMutation)(nil)

// asynctaskOption allows management of the mutation configuration using functional options.
type asynctaskOption func(*AsyncTaskMutation)

// newAsyncTaskMutation creates new mutation for the AsyncTask entity.
func newAsyncTaskMutation(c config, op Op, opts ...asynctaskOption) *AsyncTaskMutation {
	m := &AsyncTaskMutation{
		config:        c,
		op:            op,
		typ:           TypeAsyncTask,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAsyncTaskID sets the ID field of the mutation.
func withAsyncTaskID(id int64) asynctaskOption {
	return func(m *AsyncTaskMutation) {
		var (
			err   error
			once  sync.Once
			value *AsyncTask
		)
		m.oldValue = func(ctx context.Context) (*AsyncTask, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AsyncTask.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAsyncTask sets the old AsyncTask of the mutation.
func withAsyncTask(node *AsyncTask) asynctaskOption {
	return func(m *AsyncTaskMutation) {
		m.oldValue = func(context.Context) (*AsyncTask, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AsyncTaskMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AsyncTaskMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AsyncTask entities.
func (m *AsyncTaskMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AsyncTaskMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AsyncTaskMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AsyncTask.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTaskID sets the "task_id" field.
func (m *AsyncTaskMutation) SetTaskID(s string) {
	m.task_id = &s
}

// TaskID returns the value of the "task_id" field in the mutation.
func (m *AsyncTaskMutation) TaskID() (r string, exists bool) {
	v := m.task_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTaskID returns the old "task_id" field's value of the AsyncTask entity.
// If the AsyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AsyncTaskMutation) OldTaskID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTaskID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTaskID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTaskID: %w", err)
	}
	return oldValue.TaskID, nil
}

// ResetTaskID resets all changes to the "task_id" field.
func (m *AsyncTaskMutation) ResetTaskID() {
	m.task_id = nil
}

// SetTaskType sets the "task_type" field.
func (m *AsyncTaskMutation) SetTaskType(s string) {
	m.task_type = &s
}

// TaskType returns the value of the "task_type" field in the mutation.
func (m *AsyncTaskMutation) TaskType() (r string, exists bool) {
	v := m.task_type
	if v == nil {
		return
	}
	return *v, true
}

// OldTaskType returns the old "task_type" field's value of the AsyncTask entity.
// If the AsyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AsyncTaskMutation) OldTaskType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTaskType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTaskType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTaskType: %w", err)
	}
	return oldValue.TaskType, nil
}

// ResetTaskType resets all changes to the "task_type" field.
func (m *AsyncTaskMutation) ResetTaskType() {
	m.task_type = nil
}

// SetTaskName sets the "task_name" field.
func (m *AsyncTaskMutation) SetTaskName(s string) {
	m.task_name = &s
}

// TaskName returns the value of the "task_name" field in the mutation.
func (m *AsyncTaskMutation) TaskName() (r string, exists bool) {
	v := m.task_name
	if v == nil {
		return
	}
	return *v, true
}

// OldTaskName returns the old "task_name" field's value of the AsyncTask entity.
// If the AsyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AsyncTaskMutation) OldTaskName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTaskName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTaskName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTaskName: %w", err)
	}
	return oldValue.TaskName, nil
}

// ResetTaskName resets all changes to the "task_name" field.
func (m *AsyncTaskMutation) ResetTaskName() {
	m.task_name = nil
}

// SetTaskData sets the "task_data" field.
func (m *AsyncTaskMutation) SetTaskData(s string) {
	m.task_data = &s
}

// TaskData returns the value of the "task_data" field in the mutation.
func (m *AsyncTaskMutation) TaskData() (r string, exists bool) {
	v := m.task_data
	if v == nil {
		return
	}
	return *v, true
}

// OldTaskData returns the old "task_data" field's value of the AsyncTask entity.
// If the AsyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AsyncTaskMutation) OldTaskData(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTaskData is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTaskData requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTaskData: %w", err)
	}
	return oldValue.TaskData, nil
}

// ResetTaskData resets all changes to the "task_data" field.
func (m *AsyncTaskMutation) ResetTaskData() {
	m.task_data = nil
}

// SetState sets the "state" field.
func (m *AsyncTaskMutation) SetState(s string) {
	m.state = &s
}

// State returns the value of the "state" field in the mutation.
func (m *AsyncTaskMutation) State() (r string, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the AsyncTask entity.
// If the AsyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AsyncTaskMutation) OldState(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// ResetState resets all changes to the "state" field.
func (m *AsyncTaskMutation) ResetState() {
	m.state = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *AsyncTaskMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AsyncTaskMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AsyncTask entity.
// If the AsyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AsyncTaskMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AsyncTaskMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AsyncTaskMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AsyncTaskMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the AsyncTask entity.
// If the AsyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AsyncTaskMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AsyncTaskMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the AsyncTaskMutation builder.
func (m *AsyncTaskMutation) Where(ps ...predicate.AsyncTask) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AsyncTaskMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AsyncTaskMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AsyncTask, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AsyncTaskMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AsyncTaskMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AsyncTask).
func (m *AsyncTaskMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AsyncTaskMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.task_id != nil {
		fields = append(fields, asynctask.FieldTaskID)
	}
	if m.task_type != nil {
		fields = append(fields, asynctask.FieldTaskType)
	}
	if m.task_name != nil {
		fields = append(fields, asynctask.FieldTaskName)
	}
	if m.task_data != nil {
		fields = append(fields, asynctask.FieldTaskData)
	}
	if m.state != nil {
		fields = append(fields, asynctask.FieldState)
	}
	if m.created_at != nil {
		fields = append(fields, asynctask.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, asynctask.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AsyncTaskMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case asynctask.FieldTaskID:
		return m.TaskID()
	case asynctask.FieldTaskType:
		return m.TaskType()
	case asynctask.FieldTaskName:
		return m.TaskName()
	case asynctask.FieldTaskData:
		return m.TaskData()
	case asynctask.FieldState:
		return m.State()
	case asynctask.FieldCreatedAt:
		return m.CreatedAt()
	case asynctask.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AsyncTaskMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case asynctask.FieldTaskID:
		return m.OldTaskID(ctx)
	case asynctask.FieldTaskType:
		return m.OldTaskType(ctx)
	case asynctask.FieldTaskName:
		return m.OldTaskName(ctx)
	case asynctask.FieldTaskData:
		return m.OldTaskData(ctx)
	case asynctask.FieldState:
		return m.OldState(ctx)
	case asynctask.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case asynctask.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AsyncTask field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AsyncTaskMutation) SetField(name string, value ent.Value) error {
	switch name {
	case asynctask.FieldTaskID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTaskID(v)
		return nil
	case asynctask.FieldTaskType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTaskType(v)
		return nil
	case asynctask.FieldTaskName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTaskName(v)
		return nil
	case asynctask.FieldTaskData:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTaskData(v)
		return nil
	case asynctask.FieldState:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	case asynctask.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case asynctask.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AsyncTask field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AsyncTaskMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AsyncTaskMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AsyncTaskMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AsyncTask numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AsyncTaskMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AsyncTaskMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AsyncTaskMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AsyncTask nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AsyncTaskMutation) ResetField(name string) error {
	switch name {
	case asynctask.FieldTaskID:
		m.ResetTaskID()
		return nil
	case asynctask.FieldTaskType:
		m.ResetTaskType()
		return nil
	case asynctask.FieldTaskName:
		m.ResetTaskName()
		return nil
	case asynctask.FieldTaskData:
		m.ResetTaskData()
		return nil
	case asynctask.FieldState:
		m.ResetState()
		return nil
	case asynctask.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case asynctask.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown AsyncTask field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AsyncTaskMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AsyncTaskMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AsyncTaskMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AsyncTaskMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AsyncTaskMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AsyncTaskMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AsyncTaskMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AsyncTask unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AsyncTaskMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AsyncTask edge %s", name)
}

// PAHeadMutation represents an operation that mutates the PAHead nodes in the graph.
type PAHeadMutation struct {
	config
	op              Op
	typ             string
	id              *int64
	code            *string
	state           *string
	pay_amount      *string
	applicant       *string
	department_code *string
	supplier_code   *string
	is_adv          *bool
	has_invoice     *bool
	remark          *string
	created_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*PAHead, error)
	predicates      []predicate.PAHead
}

var _ ent.Mutation = (*PAHeadMutation)(nil)

// paheadOption allows management of the mutation configuration using functional options.
type paheadOption func(*PAHeadMutation)

// newPAHeadMutation creates new mutation for the PAHead entity.
func newPAHeadMutation(c config, op Op, opts ...paheadOption) *PAHeadMutation {
	m := &PAHeadMutation{
		config:        c,
		op:            op,
		typ:           TypePAHead,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPAHeadID sets the ID field of the mutation.
func withPAHeadID(id int64) paheadOption {
	return func(m *PAHeadMutation) {
		var (
			err   error
			once  sync.Once
			value *PAHead
		)
		m.oldValue = func(ctx context.Context) (*PAHead, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PAHead.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPAHead sets the old PAHead of the mutation.
func withPAHead(node *PAHead) paheadOption {
	return func(m *PAHeadMutation) {
		m.oldValue = func(context.Context) (*PAHead, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PAHeadMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PAHeadMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PAHead entities.
func (m *PAHeadMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PAHeadMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PAHeadMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PAHead.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCode sets the "code" field.
func (m *PAHeadMutation) SetCode(s string) {
	m.code = &s
}

// Code returns the value of the "code" field in the mutation.
func (m *PAHeadMutation) Code() (r string, exists bool) {
	v := m.code
	if v == nil {
		return
	}
	return *v, true
}

// OldCode returns the old "code" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCode: %w", err)
	}
	return oldValue.Code, nil
}

// ResetCode resets all changes to the "code" field.
func (m *PAHeadMutation) ResetCode() {
	m.code = nil
}

// SetState sets the "state" field.
func (m *PAHeadMutation) SetState(s string) {
	m.state = &s
}

// State returns the value of the "state" field in the mutation.
func (m *PAHeadMutation) State() (r string, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldState(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// ResetState resets all changes to the "state" field.
func (m *PAHeadMutation) ResetState() {
	m.state = nil
}

// SetPayAmount sets the "pay_amount" field.
func (m *PAHeadMutation) SetPayAmount(s string) {
	m.pay_amount = &s
}

// PayAmount returns the value of the "pay_amount" field in the mutation.
func (m *PAHeadMutation) PayAmount() (r string, exists bool) {
	v := m.pay_amount
	if v == nil {
		return
	}
	return *v, true
}

// OldPayAmount returns the old "pay_amount" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldPayAmount(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPayAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPayAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPayAmount: %w", err)
	}
	return oldValue.PayAmount, nil
}

// ResetPayAmount resets all changes to the "pay_amount" field.
func (m *PAHeadMutation) ResetPayAmount() {
	m.pay_amount = nil
}

// SetApplicant sets the "applicant" field.
func (m *PAHeadMutation) SetApplicant(s string) {
	m.applicant = &s
}

// Applicant returns the value of the "applicant" field in the mutation.
func (m *PAHeadMutation) Applicant() (r string, exists bool) {
	v := m.applicant
	if v == nil {
		return
	}
	return *v, true
}

// OldApplicant returns the old "applicant" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldApplicant(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldApplicant is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldApplicant requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldApplicant: %w", err)
	}
	return oldValue.Applicant, nil
}

// ResetApplicant resets all changes to the "applicant" field.
func (m *PAHeadMutation) ResetApplicant() {
	m.applicant = nil
}

// SetDepartmentCode sets the "department_code" field.
func (m *PAHeadMutation) SetDepartmentCode(s string) {
	m.department_code = &s
}

// DepartmentCode returns the value of the "department_code" field in the mutation.
func (m *PAHeadMutation) DepartmentCode() (r string, exists bool) {
	v := m.department_code
	if v == nil {
		return
	}
	return *v, true
}

// OldDepartmentCode returns the old "department_code" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldDepartmentCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDepartmentCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDepartmentCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDepartmentCode: %w", err)
	}
	return oldValue.DepartmentCode, nil
}

// ClearDepartmentCode clears the value of the "department_code" field.
func (m *PAHeadMutation) ClearDepartmentCode() {
	m.department_code = nil
	m.clearedFields[pahead.FieldDepartmentCode] = struct{}{}
}

// DepartmentCodeCleared returns if the "department_code" field was cleared in this mutation.
func (m *PAHeadMutation) DepartmentCodeCleared() bool {
	_, ok := m.clearedFields[pahead.FieldDepartmentCode]
	return ok
}

// ResetDepartmentCode resets all changes to the "department_code" field.
func (m *PAHeadMutation) ResetDepartmentCode() {
	m.department_code = nil
	delete(m.clearedFields, pahead.FieldDepartmentCode)
}

// SetSupplierCode sets the "supplier_code" field.
func (m *PAHeadMutation) SetSupplierCode(s string) {
	m.supplier_code = &s
}

// SupplierCode returns the value of the "supplier_code" field in the mutation.
func (m *PAHeadMutation) SupplierCode() (r string, exists bool) {
	v := m.supplier_code
	if v == nil {
		return
	}
	return *v, true
}

// OldSupplierCode returns the old "supplier_code" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldSupplierCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSupplierCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSupplierCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSupplierCode: %w", err)
	}
	return oldValue.SupplierCode, nil
}

// ResetSupplierCode resets all changes to the "supplier_code" field.
func (m *PAHeadMutation) ResetSupplierCode() {
	m.supplier_code = nil
}

// SetIsAdv sets the "is_adv" field.
func (m *PAHeadMutation) SetIsAdv(b bool) {
	m.is_adv = &b
}

// IsAdv returns the value of the "is_adv" field in the mutation.
func (m *PAHeadMutation) IsAdv() (r bool, exists bool) {
	v := m.is_adv
	if v == nil {
		return
	}
	return *v, true
}

// OldIsAdv returns the old "is_adv" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldIsAdv(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsAdv is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsAdv requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsAdv: %w", err)
	}
	return oldValue.IsAdv, nil
}

// ResetIsAdv resets all changes to the "is_adv" field.
func (m *PAHeadMutation) ResetIsAdv() {
	m.is_adv = nil
}

// SetHasInvoice sets the "has_invoice" field.
func (m *PAHeadMutation) SetHasInvoice(b bool) {
	m.has_invoice = &b
}

// HasInvoice returns the value of the "has_invoice" field in the mutation.
func (m *PAHeadMutation) HasInvoice() (r bool, exists bool) {
	v := m.has_invoice
	if v == nil {
		return
	}
	return *v, true
}

// OldHasInvoice returns the old "has_invoice" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldHasInvoice(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHasInvoice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHasInvoice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHasInvoice: %w", err)
	}
	return oldValue.HasInvoice, nil
}

// ResetHasInvoice resets all changes to the "has_invoice" field.
func (m *PAHeadMutation) ResetHasInvoice() {
	m.has_invoice = nil
}

// SetRemark sets the "remark" field.
func (m *PAHeadMutation) SetRemark(s string) {
	m.remark = &s
}

// Remark returns the value of the "remark" field in the mutation.
func (m *PAHeadMutation) Remark() (r string, exists bool) {
	v := m.remark
	if v == nil {
		return
	}
	return *v, true
}

// OldRemark returns the old "remark" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldRemark(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRemark is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRemark requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRemark: %w", err)
	}
	return oldValue.Remark, nil
}

// ResetRemark resets all changes to the "remark" field.
func (m *PAHeadMutation) ResetRemark() {
	m.remark = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *PAHeadMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PAHeadMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PAHeadMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PAHeadMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PAHeadMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the PAHead entity.
// If the PAHead object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PAHeadMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PAHeadMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the PAHeadMutation builder.
func (m *PAHeadMutation) Where(ps ...predicate.PAHead) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PAHeadMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PAHeadMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PAHead, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PAHeadMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PAHeadMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PAHead).
func (m *PAHeadMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PAHeadMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.code != nil {
		fields = append(fields, pahead.FieldCode)
	}
	if m.state != nil {
		fields = append(fields, pahead.FieldState)
	}
	if m.pay_amount != nil {
		fields = append(fields, pahead.FieldPayAmount)
	}
	if m.applicant != nil {
		fields = append(fields, pahead.FieldApplicant)
	}
	if m.department_code != nil {
		fields = append(fields, pahead.FieldDepartmentCode)
	}
	if m.supplier_code != nil {
		fields = append(fields, pahead.FieldSupplierCode)
	}
	if m.is_adv != nil {
		fields = append(fields, pahead.FieldIsAdv)
	}
	if m.has_invoice != nil {
		fields = append(fields, pahead.FieldHasInvoice)
	}
	if m.remark != nil {
		fields = append(fields, pahead.FieldRemark)
	}
	if m.created_at != nil {
		fields = append(fields, pahead.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, pahead.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PAHeadMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pahead.FieldCode:
		return m.Code()
	case pahead.FieldState:
		return m.State()
	case pahead.FieldPayAmount:
		return m.PayAmount()
	case pahead.FieldApplicant:
		return m.Applicant()
	case pahead.FieldDepartmentCode:
		return m.DepartmentCode()
	case pahead.FieldSupplierCode:
		return m.SupplierCode()
	case pahead.FieldIsAdv:
		return m.IsAdv()
	case pahead.FieldHasInvoice:
		return m.HasInvoice()
	case pahead.FieldRemark:
		return m.Remark()
	case pahead.FieldCreatedAt:
		return m.CreatedAt()
	case pahead.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PAHeadMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pahead.FieldCode:
		return m.OldCode(ctx)
	case pahead.FieldState:
		return m.OldState(ctx)
	case pahead.FieldPayAmount:
		return m.OldPayAmount(ctx)
	case pahead.FieldApplicant:
		return m.OldApplicant(ctx)
	case pahead.FieldDepartmentCode:
		return m.OldDepartmentCode(ctx)
	case pahead.FieldSupplierCode:
		return m.OldSupplierCode(ctx)
	case pahead.FieldIsAdv:
		return m.OldIsAdv(ctx)
	case pahead.FieldHasInvoice:
		return m.OldHasInvoice(ctx)
	case pahead.FieldRemark:
		return m.OldRemark(ctx)
	case pahead.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case pahead.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PAHead field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PAHeadMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pahead.FieldCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCode(v)
		return nil
	case pahead.FieldState:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	case pahead.FieldPayAmount:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPayAmount(v)
		return nil
	case pahead.FieldApplicant:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetApplicant(v)
		return nil
	case pahead.FieldDepartmentCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDepartmentCode(v)
		return nil
	case pahead.FieldSupplierCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSupplierCode(v)
		return nil
	case pahead.FieldIsAdv:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsAdv(v)
		return nil
	case pahead.FieldHasInvoice:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHasInvoice(v)
		return nil
	case pahead.FieldRemark:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRemark(v)
		return nil
	case pahead.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case pahead.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PAHead field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PAHeadMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PAHeadMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PAHeadMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown PAHead numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PAHeadMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(pahead.FieldDepartmentCode) {
		fields = append(fields, pahead.FieldDepartmentCode)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PAHeadMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PAHeadMutation) ClearField(name string) error {
	switch name {
	case pahead.FieldDepartmentCode:
		m.ClearDepartmentCode()
		return nil
	}
	return fmt.Errorf("unknown PAHead nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PAHeadMutation) ResetField(name string) error {
	switch name {
	case pahead.FieldCode:
		m.ResetCode()
		return nil
	case pahead.FieldState:
		m.ResetState()
		return nil
	case pahead.FieldPayAmount:
		m.ResetPayAmount()
		return nil
	case pahead.FieldApplicant:
		m.ResetApplicant()
		return nil
	case pahead.FieldDepartmentCode:
		m.ResetDepartmentCode()
		return nil
	case pahead.FieldSupplierCode:
		m.ResetSupplierCode()
		return nil
	case pahead.FieldIsAdv:
		m.ResetIsAdv()
		return nil
	case pahead.FieldHasInvoice:
		m.ResetHasInvoice()
		return nil
	case pahead.FieldRemark:
		m.ResetRemark()
		return nil
	case pahead.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case pahead.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown PAHead field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PAHeadMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PAHeadMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PAHeadMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PAHeadMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PAHeadMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PAHeadMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PAHeadMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PAHead unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PAHeadMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PAHead edge %s", name)
}

// PARowMutation represents an operation that mutates the PARow nodes in the graph.
type PARowMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	head_code     *string
	row_code      *string
	grn_count     *int32
	addgrn_count  *int32
	grn_amount    *string
	pay_amount    *string
	description   *string
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*PARow, error)
	predicates    []predicate.PARow
}

var _ ent.Mutation = (*PARowMutation)(nil)

// parowOption allows management of the mutation configuration using functional options.
type parowOption func(*PARowMutation)

// newPARowMutation creates new mutation for the PARow entity.
func newPARowMutation(c config, op Op, opts ...parowOption) *PARowMutation {
	m := &PARowMutation{
		config:        c,
		op:            op,
		typ:           TypePARow,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPARowID sets the ID field of the mutation.
func withPARowID(id int64) parowOption {
	return func(m *PARowMutation) {
		var (
			err   error
			once  sync.Once
			value *PARow
		)
		m.oldValue = func(ctx context.Context) (*PARow, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PARow.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPARow sets the old PARow of the mutation.
func withPARow(node *PARow) parowOption {
	return func(m *PARowMutation) {
		m.oldValue = func(context.Context) (*PARow, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PARowMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PARowMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PARow entities.
func (m *PARowMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PARowMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PARowMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PARow.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetHeadCode sets the "head_code" field.
func (m *PARowMutation) SetHeadCode(s string) {
	m.head_code = &s
}

// HeadCode returns the value of the "head_code" field in the mutation.
func (m *PARowMutation) HeadCode() (r string, exists bool) {
	v := m.head_code
	if v == nil {
		return
	}
	return *v, true
}

// OldHeadCode returns the old "head_code" field's value of the PARow entity.
// If the PARow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PARowMutation) OldHeadCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeadCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeadCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeadCode: %w", err)
	}
	return oldValue.HeadCode, nil
}

// ResetHeadCode resets all changes to the "head_code" field.
func (m *PARowMutation) ResetHeadCode() {
	m.head_code = nil
}

// SetRowCode sets the "row_code" field.
func (m *PARowMutation) SetRowCode(s string) {
	m.row_code = &s
}

// RowCode returns the value of the "row_code" field in the mutation.
func (m *PARowMutation) RowCode() (r string, exists bool) {
	v := m.row_code
	if v == nil {
		return
	}
	return *v, true
}

// OldRowCode returns the old "row_code" field's value of the PARow entity.
// If the PARow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PARowMutation) OldRowCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRowCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRowCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRowCode: %w", err)
	}
	return oldValue.RowCode, nil
}

// ResetRowCode resets all changes to the "row_code" field.
func (m *PARowMutation) ResetRowCode() {
	m.row_code = nil
}

// SetGrnCount sets the "grn_count" field.
func (m *PARowMutation) SetGrnCount(i int32) {
	m.grn_count = &i
	m.addgrn_count = nil
}

// GrnCount returns the value of the "grn_count" field in the mutation.
func (m *PARowMutation) GrnCount() (r int32, exists bool) {
	v := m.grn_count
	if v == nil {
		return
	}
	return *v, true
}

// OldGrnCount returns the old "grn_count" field's value of the PARow entity.
// If the PARow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PARowMutation) OldGrnCount(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGrnCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGrnCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGrnCount: %w", err)
	}
	return oldValue.GrnCount, nil
}

// AddGrnCount adds i to the "grn_count" field.
func (m *PARowMutation) AddGrnCount(i int32) {
	if m.addgrn_count != nil {
		*m.addgrn_count += i
	} else {
		m.addgrn_count = &i
	}
}

// AddedGrnCount returns the value that was added to the "grn_count" field in this mutation.
func (m *PARowMutation) AddedGrnCount() (r int32, exists bool) {
	v := m.addgrn_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetGrnCount resets all changes to the "grn_count" field.
func (m *PARowMutation) ResetGrnCount() {
	m.grn_count = nil
	m.addgrn_count = nil
}

// SetGrnAmount sets the "grn_amount" field.
func (m *PARowMutation) SetGrnAmount(s string) {
	m.grn_amount = &s
}

// GrnAmount returns the value of the "grn_amount" field in the mutation.
func (m *PARowMutation) GrnAmount() (r string, exists bool) {
	v := m.grn_amount
	if v == nil {
		return
	}
	return *v, true
}

// OldGrnAmount returns the old "grn_amount" field's value of the PARow entity.
// If the PARow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PARowMutation) OldGrnAmount(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGrnAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGrnAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGrnAmount: %w", err)
	}
	return oldValue.GrnAmount, nil
}

// ResetGrnAmount resets all changes to the "grn_amount" field.
func (m *PARowMutation) ResetGrnAmount() {
	m.grn_amount = nil
}

// SetPayAmount sets the "pay_amount" field.
func (m *PARowMutation) SetPayAmount(s string) {
	m.pay_amount = &s
}

// PayAmount returns the value of the "pay_amount" field in the mutation.
func (m *PARowMutation) PayAmount() (r string, exists bool) {
	v := m.pay_amount
	if v == nil {
		return
	}
	return *v, true
}

// OldPayAmount returns the old "pay_amount" field's value of the PARow entity.
// If the PARow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PARowMutation) OldPayAmount(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPayAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPayAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPayAmount: %w", err)
	}
	return oldValue.PayAmount, nil
}

// ResetPayAmount resets all changes to the "pay_amount" field.
func (m *PARowMutation) ResetPayAmount() {
	m.pay_amount = nil
}

// SetDescription sets the "description" field.
func (m *PARowMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *PARowMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the PARow entity.
// If the PARow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PARowMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *PARowMutation) ResetDescription() {
	m.description = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *PARowMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PARowMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PARow entity.
// If the PARow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PARowMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PARowMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PARowMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PARowMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the PARow entity.
// If the PARow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PARowMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PARowMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the PARowMutation builder.
func (m *PARowMutation) Where(ps ...predicate.PARow) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PARowMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PARowMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PARow, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PARowMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PARowMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PARow).
func (m *PARowMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PARowMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.head_code != nil {
		fields = append(fields, parow.FieldHeadCode)
	}
	if m.row_code != nil {
		fields = append(fields, parow.FieldRowCode)
	}
	if m.grn_count != nil {
		fields = append(fields, parow.FieldGrnCount)
	}
	if m.grn_amount != nil {
		fields = append(fields, parow.FieldGrnAmount)
	}
	if m.pay_amount != nil {
		fields = append(fields, parow.FieldPayAmount)
	}
	if m.description != nil {
		fields = append(fields, parow.FieldDescription)
	}
	if m.created_at != nil {
		fields = append(fields, parow.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, parow.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PARowMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case parow.FieldHeadCode:
		return m.HeadCode()
	case parow.FieldRowCode:
		return m.RowCode()
	case parow.FieldGrnCount:
		return m.GrnCount()
	case parow.FieldGrnAmount:
		return m.GrnAmount()
	case parow.FieldPayAmount:
		return m.PayAmount()
	case parow.FieldDescription:
		return m.Description()
	case parow.FieldCreatedAt:
		return m.CreatedAt()
	case parow.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PARowMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case parow.FieldHeadCode:
		return m.OldHeadCode(ctx)
	case parow.FieldRowCode:
		return m.OldRowCode(ctx)
	case parow.FieldGrnCount:
		return m.OldGrnCount(ctx)
	case parow.FieldGrnAmount:
		return m.OldGrnAmount(ctx)
	case parow.FieldPayAmount:
		return m.OldPayAmount(ctx)
	case parow.FieldDescription:
		return m.OldDescription(ctx)
	case parow.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case parow.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PARow field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PARowMutation) SetField(name string, value ent.Value) error {
	switch name {
	case parow.FieldHeadCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeadCode(v)
		return nil
	case parow.FieldRowCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRowCode(v)
		return nil
	case parow.FieldGrnCount:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGrnCount(v)
		return nil
	case parow.FieldGrnAmount:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGrnAmount(v)
		return nil
	case parow.FieldPayAmount:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPayAmount(v)
		return nil
	case parow.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case parow.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case parow.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PARow field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PARowMutation) AddedFields() []string {
	var fields []string
	if m.addgrn_count != nil {
		fields = append(fields, parow.FieldGrnCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PARowMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case parow.FieldGrnCount:
		return m.AddedGrnCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PARowMutation) AddField(name string, value ent.Value) error {
	switch name {
	case parow.FieldGrnCount:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGrnCount(v)
		return nil
	}
	return fmt.Errorf("unknown PARow numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PARowMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PARowMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PARowMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PARow nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PARowMutation) ResetField(name string) error {
	switch name {
	case parow.FieldHeadCode:
		m.ResetHeadCode()
		return nil
	case parow.FieldRowCode:
		m.ResetRowCode()
		return nil
	case parow.FieldGrnCount:
		m.ResetGrnCount()
		return nil
	case parow.FieldGrnAmount:
		m.ResetGrnAmount()
		return nil
	case parow.FieldPayAmount:
		m.ResetPayAmount()
		return nil
	case parow.FieldDescription:
		m.ResetDescription()
		return nil
	case parow.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case parow.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown PARow field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PARowMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PARowMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PARowMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PARowMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PARowMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PARowMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PARowMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PARow unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PARowMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PARow edge %s", name)
}
